### ISSUE TITLE
Cache bundle gems not working

### ISSUE THREAD

**Issue by jeffreytse** [jeffreytse/jekyll-deploy-action#14]
Since getting OS name from `/etc/os-release`  and saving to the bundle's folder is always failed, this causes caching bundle gems not working.

**Comment by jeffreytse** [comment]
We should also use below cache key for the `actions/cache`.

```yml
# Use GitHub Actions' cache to cache dependencies on servers
- uses: actions/cache@v2
  with:
    path: vendor/bundle
    key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/os-name') }}
    restore-keys: |
      ${{ runner.os }}-gems-
```

**Comment by jeffreytse** [comment]
We can use a VERSION secrect for updating the cache as below code snippet.

```yml
# Use GitHub Actions' cache to cache dependencies on servers
- uses: actions/cache@v2
  with:
    path: vendor/bundle
    key: ${{ runner.os }}-gems-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Gemfile.lock') }}
    restore-keys: |
      ${{ runner.os }}-gems-
```
