### ISSUE TITLE
Suggestion for project

### ISSUE THREAD

**Issue by Benau** [jeffreytse/jekyll-deploy-action#31]
In order to port from official github-page gem to jeykll +  this action, I need to use this deploy file:
```yml
name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set GitHub variables
        run: |
          echo "repository: $GITHUB_REPOSITORY" >> _config.yml
          #echo "url: https://$(echo $GITHUB_REPOSITORY | cut -d '/' -f1).github.io" >> _config.yml
          #echo "baseurl: /$(basename $GITHUB_REPOSITORY)" >> _config.yml
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: jeffreytse/jekyll-deploy-action@v0.3.1
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          pre_build_commands: export JEKYLL_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
```
Basically I need an extra deps "jekyll-github-metadata" so it can auto set site.url + baseurl, otherwise i need to set it manually (see the commented out lines)

But you don't seem to "export" JEKYLL_GITHUB_TOKEN with the token so I need an extra step, would be good if you can add that in your entrypoint.sh...

I still need to set repository: maunally though (but if I use official github-page gem it auto set), but that's minor issue
