### ISSUE TITLE
Github Actions not caching _site

### ISSUE THREAD

**Issue by datapolitical** [jeffreytse/jekyll-deploy-action#4]
I'm running into an odd issue where every time my site deploys it has to re-generate *all* of the webp image files, because it can't find them in the destination directory (despite being in the same folder with the originals). The code runs fine locally, but that's because the _site folder is still there. But with this plugin that _site data disappears after it's pushed.

Edit: *I should add that I had to fork the action and edit it to run with ubuntu-latest and bash in order to get the thing to run the webp plugin. If there's a way to update it to support the plugin using the current setup.* https://github.com/datapolitical/jekyll-deploy-action

So I'm just sort of trying to figure out how to make the two work together correctly, and any thoughts you might have would be very welcome. 

https://github.com/sverrirs/jekyll-webp/blob/master/lib/jekyll-webp/webpGenerator.rb

**Comment by jeffreytse** [comment]
Hi @datapolitical 

Thanks for your reporting, I will work to solve this problem.

Thanks and regards

**Comment by datapolitical** [comment]
Thanks!

**Comment by datapolitical** [comment]
Turns out this is not working and my site build has ballooned to over 16 minutes because of the responsive image plugin I'm using. 

The action runs, the cache hit happens, but nothing is being stored in the cache. 
I use this:

```
# Use GitHub Actions' cache to cache site on servers
  - uses: actions/cache@v2
    with:
      path: _site
      key: ${{ runner.os }}-site-${{ hashFiles('**/index.html') }}
      restore-keys: |
        ${{ runner.os }}-site-
```
from here: https://github.com/datapolitical/chrisfnicholson.github.io/blob/main/.github/workflows/build-jekyll.yml

But the response is: 
Received 22 of 22 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (22 B).

I assume there's something up with my path but it's exactly what was suggested above.

**Comment by jeffreytse** [comment]
Hi @datapolitical 

I saw that you're not using this jekyll-deploy-action from here https://github.com/datapolitical/chrisfnicholson.github.io/blob/481414b45213dafaf635ba4b980ffa0050050966/.github/workflows/build-jekyll.yml#L54, so I think you cache a wrong site ouput folder.

Thanks and regards

**Comment by datapolitical** [comment]
It's the same action I just updated it to run in Ubuntu and added a few extra dependencies so my site would build properly. Shouldn't change the build folder.

https://github.com/jeffreytse/jekyll-deploy-action/compare/master...datapolitical:master

**Comment by jeffreytse** [comment]
Could you change your action to `jeffreytse/jekyll-deploy-action@v0.2.0` and try again? Maybe it settle your issue abou the `_site` folder has not been cached. : )

**Comment by datapolitical** [comment]
Didn't build because of all the dependencies I load early in the script conflict with what your code expects, but I need them to run imagemagick ![image](https://user-images.githubusercontent.com/696957/111900170-39cead80-89ee-11eb-9bb6-351f9a5b9296.png)

**Comment by jeffreytse** [comment]
Hi @datapolitical , my deploy action has added `imagemagick` package to the system enviroment, so I don't know why it has the conflicts, could you provide me the action log to analysis?

**Comment by datapolitical** [comment]
This is the issue I'm talking about. It was a lot of work to make it compatible. 

https://github.com/sverrirs/jekyll-webp/issues/15#issuecomment-739579629

**Comment by jeffreytse** [comment]
Hi @datapolitical , don't worry, I will try to help you to settle down this issue, please be patient. : )

**Comment by jeffreytse** [comment]
Hi @datapolitical 

Thanks for the patience and currently this issue has been addressed and fixed.

- You don't need to use a fork's action and I have test with the action `jeffreytse/jekyll-deploy-action@master` and it has no any dependencies issue. ([See here](https://github.com/jeffreytse/chrisfnicholson.github.io/runs/2159506586?check_suite_focus=true) and [the website](https://jeffreytse.github.io/chrisfnicholson.github.io/))
- The output folder is not the `_site` and you should cache  `build` folder as follow code snippet.

```yml
      # Use GitHub Actions' cache to cache site on servers
      - uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('**/index.html') }}
          restore-keys: |
            ${{ runner.os }}-build-
```

Thanks and regards
