### ISSUE TITLE
How to test the action?

### ISSUE THREAD

**Issue by MaxGhenis** [jeffreytse/jekyll-deploy-action#5]
I'd like a testing action that runs on PRs before merging, which builds but doesn't deploy. Is this possible?

**Comment by jeffreytse** [comment]
Hi @MaxGhenis 

Yes,  you can test it before merging as below:

1. Create a branch called `test` for your fork.

```bash
git checkout --orphan test
git rm -rf .
git commit --allow-empty -m "initial commit"
git push origin test
```

2. Change the action option `branch` to `test`.

```yaml
# Use GitHub Deploy Action to build and deploy to Github
 - uses: jeffreytse/jekyll-deploy-action@v0.1.4
      with:
        provider: 'github'
        token: ${{ secrets.GH_TOKEN }} # It's your Personal Access Token(PAT)
        repository: ''             # Default is current repository
        branch: 'test'         # Default is gh-pages for github provider
        jekyll_src: './'           # Default is root directory
        jekyll_cfg: '_config.yml'  # Default is _config.yml
        jekyll_baseurl: ''         # Default is according to _config.yml
        bundler_ver: '>=0'         # Default is latest bundler version
        cname: ''                  # Default is to not use a cname
        actor: ''                  # Default is the GITHUB_ACTOR
```

3. Create your [PAT](https://github.com/settings/tokens) (Personal Access Token).

- Go to your repository’s Settings and then switch to the Secrets tab.
- Create a token named `GH_TOKEN` (important) using the value copied.

4. Push this to your forking repository 


Thanks and regards
