### ISSUE TITLE
Could not find JS runtime 

### ISSUE THREAD

**Issue by rohitjain00** [jeffreytse/jekyll-deploy-action#59]
Hi,

I'm getting this error while building
```
Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
```

As far as I've read on the internet it says that we need to install node js to rectify this issue. Do we have this dependency covered in this docker build? Also, if yes can you please take a look at the possible solution to this issue?

Here is the build link :  https://github.com/rohitjain00/rohitjain00.github.io/actions/runs/4040838762/jobs/6946852704

**Comment by jeffreytse** [comment]
Hi @rohitjain00 

Thanks for your issue, you need to install JavaScript runtime by the `pre_build_commands` option as below:

```yml
  # Standard usage
  - uses:  helaili/jekyll-action@master
    with:
      token: ${{ secrets.GH_TOKEN }}
      target_branch: 'gh-pages'
      pre_build_commands: apk --update add nodejs
```

And also welcome to star this repository for further updates in the future. : )

Thanks & Regards
