### ISSUE TITLE
gh-pages branch remains empty after push to master; pages build and deployment not triggered

### ISSUE THREAD

**Issue by lezojeda** [jeffreytse/jekyll-deploy-action#62]
Hello. If I understand correctly (correct me if I don´t please), if I commit to `master `I should expect two actions to be triggered, the custom one from the yml file and the `pages build and deployment` from github itself right? I have created the yml workflow file ander `.github/workflows/`, set up the deployment to be from `gh-pages` branch but when I commit to `master`, `gh-pages` remains empty so I get a 404 when I go to my pages url

![image](https://user-images.githubusercontent.com/35072686/225763770-53320972-ded5-43a3-a144-990e86ba0e69.png)

Thanks in advance

**Comment by lezojeda** [comment]
Fixed it. I had to configure `Workflow permissions` to "Read an write permissions" in the repo settings -> Actions -> General, to the bottom of the page. It was set to "Read repository contents and package permissions" by default.

![image](https://user-images.githubusercontent.com/35072686/225768073-adb3fb9c-033c-4746-8e6c-170f5993277f.png)

**Comment by jeffreytse** [comment]
Hi @lezojeda

Thanks for your issue, and it's so glad to hear that you've solved the problem. And welcome to star this project for further update in the future.

Thanks & Regards

**Comment by AlexHolderDeveloper** [comment]
Can confirm, this was an issue for me and the change to permissions fixed this issue for me as well. It'd be worthwhile to put a note about this in the project's readme - it's the only hurdle that I had in getting this awesome action to work!

**Comment by indie-rok** [comment]
@lezojeda Made the trick! Thank you

**Comment by davidalpert** [comment]
if you do not want to change the default workflow permissions you can also set permissions for this workflow alone.

add something like this `permissions` block to your workflow:
```
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      contents: write # read to check out code / write enables push to the configured branch (e.g. gh-pages)
      pages: write
```
