### ISSUE TITLE
how do i setup a custom domain?

### ISSUE THREAD

**Issue by ankris812** [jeffreytse/jekyll-deploy-action#67]
thats the question, where and how i set a custom domain if im using this action

**Comment by jeffreytse** [comment]
Hi @ankris812 

You can set your custom domain via option `cname` as below:

```yml
- uses: jeffreytse/jekyll-deploy-action@v0.5.0
        with:
          provider: 'github'         # Default is github
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          ...
          cname: 'www.example.com'                  # Default is to not use a cname
```
