### ISSUE TITLE
`with.repository` parameter is unable to access external repository: "The requested URL returned error: 403"

### ISSUE THREAD

**Issue by cwboden** [jeffreytse/jekyll-deploy-action#68]
# Use Case
I am attempting to use `jekyll-deploy-actions` for the following use case:
 - I have a _private_ repository that I use for taking notes and writing blog posts using Jekyll
 - I want to publish using GitHub pages, though don't want to pay for the premium subscription (required for publishing from a private repository)
 - Instead, I'd like to use this action and the `with.repository` argument to push the pages bundle to a _public_ repository that can then publish via GitHub pages for free

# Workflow Definition
Here is the definition of my GitHub workflow (from the private repository), which is configured according to the README:

```yaml
name: Deploy Github Pages

on:
    push:
        branches:
            - main
        paths:
            - .github/workflows/build-jekyll.yml
            - Website/**

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: jeffreytse/jekyll-deploy-action@master
              with:
                  branch: main
                  provider: github
                  repository: cwboden/website
                  token: ${{ secrets.GITHUB_TOKEN }}
```

When this Workflow runs, it completes the build / bundling process successfully, but fails when attempting to push to my public repo:

```
remote: Permission to cwboden/website.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/cwboden/website.git/': The requested URL returned error: 403
```

I initially thought this was a problem with the `secrets.GITHUB_TOKEN`, so I also added a PAT to the repository under the secret `GH_TOKEN` (as outlined in the README):
![image](https://github.com/jeffreytse/jekyll-deploy-action/assets/11033906/7028ac7b-6327-4d37-9afd-b4778b3e6346)

However, I end up with the same error :cry: I'm curious if the `with.repository` parameter is only supported by SSH authentication?

# Other Troubleshooting Attempts
I also tried a few other things, such as replacing the `with.token` parameter with `$GH_TOKEN` (though then the build step cannot complete), using a Legacy GitHub PAT rather than the granular ones, and by removing the authorization headers, according to [this Stack Overflow post](https://stackoverflow.com/questions/64270867/auth-error-trying-to-copy-a-repo-with-github-actions).

None of these have helped, though I can update this section as I continue troubleshooting the problem. My next step will be to take a look at how `GH_TOKEN` is used within the plugin source code. Perhaps I'm missing something there.
