### ISSUE TITLE
No such file or directory - gsl-config

### ISSUE THREAD

**Issue by iveney** [jeffreytse/jekyll-deploy-action#7]
Hi again :)

My site enabled `lsi` which leverages gem "classifier-reborn" and gem "gsl". It works fine by me locally in Mac. It also works fine with travis-ci.com (I am trying to migrate the deployment from travis-ci to github actions). It is not working with this action though.

Since `gsl` requires installing `libgsl0-dev` in ubuntu, so I added this before the sample yml. It is installed successfully. However, I am still running into the following issue: 

```
Run jeffreytse/jekyll-deploy-action@v0.1.4 ...
Starting the Jekyll Deploy Action
Initial comptible bundler
Successfully installed bundler-2.2.7
1 gem installed
Starting bundle install
...
Fetching gsl 2.1.0.3
Installing gsl 2.1.0.3 with native extensions
...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/github/workspace/vendor/bundle/ruby/2.7.0/gems/gsl-2.1.0.3/ext/gsl_native
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210127-20-1bvc9kd.rb extconf.rb
*** ERROR: missing required library to compile this module: No such file or
directory - gsl-config
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--with-gsl-version

extconf failed, exit code 1

Gem files will remain installed in
/github/workspace/vendor/bundle/ruby/2.7.0/gems/gsl-2.1.0.3 for inspection.
Results logged to
/github/workspace/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux-musl/2.7.0/gsl-2.1.0.3/gem_make.out

An error occurred while installing gsl (2.1.0.3), and Bundler cannot continue.
Make sure that `gem install gsl -v '2.1.0.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  gsl
```

I noticed there is `imagemagick` added to the action's Dockerfile, which I am also trying to install via apt-get to support a gallery plugin. Here's the exact lines I added to the yml:

```
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install packages
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y libgsl0-dev libmagick++-dev
          which gsl-config

      - uses: actions/checkout@v2
 
      # the remaining is the same as the sample
```

I am wondering if this can be solved via building into Dockerfile? It is a bit hard to debug because the trial and error nature of testing the workflow 🤕

**Comment by jeffreytse** [comment]
Hi @iveney 

Could you provide me your repository? I will fork it and help you to settle it down.

Thanks and regards

**Comment by iveney** [comment]
@jeffreytse  Thanks for the kind offer!

Here's the [repo](https://github.com/iveney/ivansiu.com/tree/test-gsl) for reproducing. Use [test-gsl](https://github.com/iveney/ivansiu.com/tree/test-gsl) branch. Here's the [full log](https://github.com/iveney/ivansiu.com/actions/runs/516114702) of failed workflow.

**Comment by jeffreytse** [comment]
Hi @iveney 

Your issue has been addressed and settled down. please update to `jekyll-deploy-action@v0.2.0`, the `build-jekyll.yml` please follow the below:

```yml
name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.2.0
        with:
          provider: 'github'
          token: ${{ secrets.GH_TOKEN }} # It's your Personal Access Token(PAT)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          bundler_ver: '>=0'         # Default is latest bundler version
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
```

Thanks and regards
