### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by 000407** [jeffreytse/jekyll-deploy-action#8]
Hello there,

I stumbled upon this.

![image](https://user-images.githubusercontent.com/21293445/107841954-f25b6d00-6e02-11eb-8fba-3996a7257172.png)

The following is my workflow.

```yml
name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.2.0
        with:
          provider: 'github'
          token: ${{ secrets.TOKEN }}
```
Any idea why this is happening?
