### ISSUE TITLE
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400

### ISSUE THREAD

**Issue by RiverOnVenus** [jeffreytse/jekyll-deploy-action#81]
Hi, I'm get this error when I use action. https://github.com/RiverOnVenus/blog/actions/runs/8502833478/job/23287509540#step:5:948

> error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
> send-pack: unexpected disconnect while reading sideband packet
> fatal: the remote end hung up unexpectedly
> Everything up-to-date

My workflow file:
```
name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      # For latest version: `jeffreytse/jekyll-deploy-action@master`
      - uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          provider: 'github'         # Default is github
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          ssh_private_key: ''        # It's your SSH private key (SSH approach)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          bundler_ver: ''            # Default is compatible bundler version (~>2.4.0)
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux)

```
I tried to find a solution online and found this thread. https://github.com/orgs/community/discussions/55820

Regards.
