### ISSUE TITLE
ruby-build version not found

### ISSUE THREAD

**Issue by ajsanjoaquin** [jeffreytse/jekyll-deploy-action#90]
I get a weird error where it does not specify which ruby-build version it was trying to find. Like #71 , I started having an error based on an update and I can build the website locally without any issue, so I decided to lock my ruby and bundler versions in the workflow file (see end of this post). 

Here is the log of the action:

```Ruby
Run jeffreytse/jekyll-deploy-action@master
  with:
    provider: github
    token: ***
    branch: gh-pages
    jekyll_src: ./
    jekyll_cfg: _config.yml
    bundler_ver: ~>2.4.0
    ruby_ver: 2.7.8.225
/usr/bin/docker run --name e1f280e530b5aaf55407da713d125c6a012f4_19213a --label 5e1f28 --workdir /github/workspace --rm -e "INPUT_PROVIDER" -e "INPUT_TOKEN" -e "INPUT_REPOSITORY" -e "INPUT_BRANCH" -e "INPUT_JEKYLL_SRC" -e "INPUT_JEKYLL_CFG" -e "INPUT_JEKYLL_BASEURL" -e "INPUT_BUNDLER_VER" -e "INPUT_RUBY_VER" -e "INPUT_CNAME" -e "INPUT_ACTOR" -e "INPUT_PRE_BUILD_COMMANDS" -e "INPUT_SSH_PRIVATE_KEY" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ajsanjoaquin.github.io/ajsanjoaquin.github.io":"/github/workspace" 5e1f28:0e530b5aaf55407da713d125c6a012f4
Starting the Jekyll Deploy Action
Initialize environment
==> Generating pacman master key. This may take some time.
gpg: Generating pacman keyring master key...
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/7ACC7FEA9DB168D7732CD503984F2324DB6B808C.rev'
gpg: Done
==> Updating trust database...
gpg: Note: third-party key signatures using the SHA1 algorithm are rejected
gpg: (use option "--allow-weak-key-signatures" to override)
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   2  signed:   5  trust: 0-, 0q, 0n, 0m, 0f, 2u
gpg: depth: 1  valid:   5  signed: 101  trust: 0-, 0q, 0n, 5m, 0f, 0u
gpg: depth: 2  valid:  77  signed:  22  trust: 77-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2024-11-09
:: Synchronizing package databases...
 core downloading...
 extra downloading...
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Package (4)             Old Version  New Version  Net Change  Download Size

core/archlinux-keyring  20240709-2   20241015-1     0.00 MiB       1.18 MiB
core/glib2              2.82.1-2     2.82.2-1       0.00 MiB       4.89 MiB
core/iana-etc           20240814-1   20241016-1     0.00 MiB       0.39 MiB
core/libarchive         3.7.6-1      3.7.7-1        0.00 MiB       0.54 MiB

Total Download Size:    6.99 MiB
Total Installed Size:  43.72 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 glib2-2.82.2-1-x86_64 downloading...
 archlinux-keyring-20241015-1-any downloading...
 libarchive-3.7.7-1-x86_64 downloading...
 iana-etc-20241016-1-any downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
upgrading iana-etc...
upgrading libarchive...
upgrading glib2...
upgrading archlinux-keyring...
==> Appending keys from archlinux.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signed 5 keys.
==> Importing owner trust values...
==> Updating trust database...
gpg: Note: third-party key signatures using the SHA1 algorithm are rejected
gpg: (use option "--allow-weak-key-signatures" to override)
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   2  signed:   5  trust: 0-, 0q, 0n, 0m, 0f, 2u
gpg: depth: 1  valid:   5  signed: 102  trust: 0-, 0q, 0n, 5m, 0f, 0u
gpg: depth: 2  valid:  78  signed:  22  trust: 78-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2024-11-18
:: Running post-transaction hooks...
(1/2) Reloading system manager configuration...
  Skipped: Current root is not booted.
(2/2) Arming ConditionNeedsUpdate...
resolving dependencies...
looking for conflicting packages...

Package (4)           New Version  Net Change  Download Size

extra/perl-error      0.17029-7      0.04 MiB       0.02 MiB
extra/perl-mailtools  2.21-9         0.10 MiB       0.06 MiB
extra/perl-timedate   2.33-7         0.08 MiB       0.03 MiB
extra/git             2.47.0-1      28.29 MiB       6.51 MiB

Total Download Size:    6.62 MiB
Total Installed Size:  28.51 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 git-2.47.0-1-x86_64 downloading...
 perl-mailtools-2.21-9-any downloading...
 perl-timedate-2.33-7-any downloading...
 perl-error-0.17029-7-any downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
installing perl-error...
installing perl-timedate...
installing perl-mailtools...
installing git...
Optional dependencies for git
    tk: gitk and git gui
    openssh: ssh transport and crypto
    perl-libwww: git svn
    perl-term-readkey: git svn and interactive.singlekey setting
    perl-io-socket-ssl: git send-email TLS support
    perl-authen-sasl: git send-email TLS support
    perl-mediawiki-api: git mediawiki support
    perl-datetime-format-iso8601: git mediawiki support
    perl-lwp-protocol-https: git mediawiki https support
    perl-cgi: gitweb (web interface) support
    python: git svn & git p4
    subversion: git svn
    org.freedesktop.secrets: keyring credential helper
    libsecret: libsecret credential helper [installed]
:: Running post-transaction hooks...
(1/4) Creating system user accounts...
Creating group 'git' with GID 972.
Creating user 'git' (git daemon user) with UID 972 and GID 972.
(2/4) Reloading system manager configuration...
  Skipped: Current root is not booted.
(3/4) Arming ConditionNeedsUpdate...
(4/4) Warn about old perl modules
Cloning into '/github/workspace/.asdf'...
Note: switching to 'ccdd47df9b73d0a22235eb06ad4c48eb57360832'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

resolving dependencies...
looking for conflicting packages...

Package (1)    New Version  Net Change  Download Size

extra/libyaml  0.2.5-3        0.18 MiB       0.06 MiB

Total Download Size:   0.06 MiB
Total Installed Size:  0.18 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 libyaml-0.2.5-3-x86_64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
installing libyaml...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Cloning into '/github/home/.asdf/repository'...
Downloading ruby-build...
Version not found

If this is a new Ruby version, you may need to update the plugin:
asdf plugin update ruby
initializing plugin repository...
```

And here is the workflow file used:
```yml
      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@master
        with:
          provider: 'github'
          token: ${{ secrets.GH_TOKEN }} # It's your Personal Access Token(PAT)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          bundler_ver: '~>2.4.0'            # >=0 is latest bundler version
          ruby_ver: '2.7.8.225'                   # Default is 3.2.0
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux)
```
