### ISSUE TITLE
Site not building with a submodule referenced in _config.yaml file

### ISSUE THREAD

**Issue by pschloss** [jeffreytse/jekyll-deploy-action#92]
I have a submodule ([`resources/`](https://github.com/riffomonas/resources)) as part of [my Jekyll repo](https://github.com/riffomonas/resources/blob/master/_sass/main.scss) that is referenced in the [`_config.yaml`](https://github.com/riffomonas/code_club/blob/master/_config.yml) file:

```
layouts_dir: /resources/_layouts
includes_dir: /resources/_includes
sass:
  sass_dir: /resources/_sass
  style: compressed
```

Unfortunately when the `jekyll-deploy-action` runs, it does not seem to be building with the submodule. The [rendered site](https://riffomonas.org/code_club/) is not getting the styling that I had been getting when building off of the `master` branch with the submodule. It should look a lot more like the [rest of the site](https://riffomonas.org/), which is styled using the sass files in `resources/`.

Any ideas what I might be missing to get the site to build using `resources/`?
