### ISSUE TITLE
`_native_parse': (/github/workspace/_config.yml): did not find expected key while parsing a block mapping at line 21 column

### ISSUE THREAD

**Issue by floriankraemer** [jeffreytse/jekyll-deploy-action#94]
I'm getting this error and I have honestly no clue why, I'm not a Ruby dev. Well, its a syntax error. 😄 But why do I get it?

```
Bundle complete! 10 Gemfile dependencies, 36 gems now installed.
Bundled gems are installed into `./vendor/bundle`
Starting jekyll build
                    ------------------------------------------------
      Jekyll 4.3.4   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/psych/parser.rb:62:in `_native_parse': (/github/workspace/_config.yml): did not find expected key while parsing a block mapping at line 21 column 1 (Psych::SyntaxError)
	from /github/workspace/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/psych/parser.rb:62:in `parse'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `load'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `block in load_file'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `open'
	from /github/workspace/vendor/bundle/ruby/3.2.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `load_file'
```

Workflow:

```
name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      # For latest version: `jeffreytse/jekyll-deploy-action@master`
      - uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'         # Default is github
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          ssh_private_key: ''        # It's your SSH private key (SSH approach)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''        # Default is according to _config.yml
          bundler_ver: ''            # Default is compatible bundler version (~>2.4.0)
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: 'bundle update'     # Installing additional dependencies (Arch Linux)
````
